services:
  backend:
    image: ghcr.io/freezeyy/devdna-backend:latest

    environment:
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}

  frontend:
    image: ghcr.io/freezeyy/devdna-frontend:latest

    ports:
      - "8080:80"